spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msdb
    username: msdb
    password: msdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # HikariCP 설정 예시

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true  # SQL 쿼리 포맷팅 설정
    show-sql: true
    hibernate:
      ddl-auto: update  # 애플리케이션 실행 시 DDL 자동 생성/업데이트 설정

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  kafka:  # kafka 설정
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


