spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msdb
    username: msdb
    password: msdb
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true


    server:
      servlet:
        encoding:
          charset: UTF-8
          enabled: true
          force: true